init: add pom and base classes
artipie/git-adapter pull request #2
Opened 2021-11-15 12:00 UTC by g4s8

Add `pom.xml` for project config. Add base classes
for handling smart-http protocol: `GitSlice` is an entrypoint,
other slices will be responsible for receive and upload pack commands.

2021-11-15 14:08 UTC, olenagerasimova requested changes
@g4s8 thanks, several comments, take a look please

2021-11-15 14:08 UTC, olenagerasimova commented on src/main/java/com/artipie/git/ReceivePackSlice.java
> +    static final class InforRefSlice extends Slice.Wrap {
seems like there is a typo in the slice name

2021-11-15 14:08 UTC, olenagerasimova commented on src/main/java/com/artipie/git/UploadPackSlice.java
> +    static final class InforRefSlice extends Slice.Wrap {
same here

2021-11-15 14:22 UTC, g4s8 commented
@olenagerasimova thanks, all fixed

2021-11-17 08:31 UTC, olenagerasimova approved these changes
@g4s8 thanks, sorry for the delay

2021-11-17 08:31 UTC, merged